# Site settings
title: Assess and Improve
email: martin.rowe@assessandimprove.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Assess and Improve: Exercises
baseurl: /jekyllblog # the subpath of your site, e.g. /blog/
url: "http://martinrowe.github.io/jekyllblog/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  martinrowe

# Build settings
markdown: kramdown
