# Site settings
title: Assess and Improve
email: martin.rowe@assessandimprove.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Assess and Improve: This is an attempt to create a site using the principles of negative space
baseurl: /jekyllblog/ # the subpath of your site, e.g. /blog/
# url: "http://www.assessandimprove.info/" # the base hostname & protocol for your site
url: "http://www.assessandimprove.info/jekyllblog/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  martinrowe

# Build settings
markdown: kramdown
