# Site settings
title: Assess and Improve
email: martin.rowe@assessandimprove.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Assess and Improve: This is an attempt to create a site using the principles of negative space
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://www.assessandimprove.info/" # the base hostname & protocol for your site
url: "martinrowe.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  martinrowe

default:
  -
  markdown_ext: "markdown,mkdown,mkdn,mkd,md,mdk"

# Build settings
markdown: kramdown
